###-------- Messages for debugging ----------###

#----counter-----#
int32 counter

##----Contact----##

#---Mode and submode---#
int32 mode_cn
int32 submode_cn

float64 lat_cn
float64 lon_cn
float32 SOG_cn # [m/s]
float32 COG_cn # [degrees]
int32 lenght_cn # [m]

float32 x_cn # [m]
float32 y_cn # [m]

##----Ownship----##

#---Mode and submode---#
int32 mode_os
int32 submode_os

float64 lat_os
float64 lon_os
float32 SOG_os # [m/s]
float32 COG_os # [degrees]
int32 lenght_os # [m]

float32 x_os # [m]
float32 y_os # [m]

#-----Start Evasion-----#
float64 Start_Evasion

#-----distance between ships-----#
float64 r # [m]
